// src/components/BookmarkGrid.tsx
import React from "react";
import { AgGridReact } from "ag-grid-react";
import { ModuleRegistry, AllCommunityModule, ColDef, themeMaterial } from "ag-grid-community";

interface Bookmark {
  id: string;
  title: string;
  url?: string;
  dateAdded?: number;
}

interface BookmarkGridProps {
  rowData: Bookmark[];
}

ModuleRegistry.registerModules([AllCommunityModule]);

const BookmarkGrid: React.FC<BookmarkGridProps> = ({ rowData }) => {
  const columnDefs: ColDef<Bookmark>[] = [
    { field: "title", headerName: "Title", sortable: true, filter: true },
    { field: "url", headerName: "URL", sortable: true, filter: true },
    { field: "dateAdded", headerName: "Date Added", sortable: true, filter: "agDateColumnFilter" },
  ];

  const defaultColDef = {
    resizable: true,
    sortable: true,
    filter: true,
  };

  const theme = themeMaterial;

  return (
    <div style={{ height: "100%", width: "100%" }}>
      <AgGridReact rowData={rowData} columnDefs={columnDefs} defaultColDef={defaultColDef} theme={theme} />
    </div>
  );
};

export default BookmarkGrid;

// minutemen-lm/src/components/BookmarkGrid.vue
<template>
  <ag-grid-vue style="width: 100%; height: 100%;" :columnDefs="columnDefs" :rowData="rowData" :theme="theme"></ag-grid-vue>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { AgGridVue } from 'ag-grid-vue3';
import { AllCommunityModule } from 'ag-grid-community';
import { ModuleRegistry } from 'ag-grid-community';
import { themeMaterial, colorSchemeDark } from 'ag-grid-community';

ModuleRegistry.registerModules([AllCommunityModule]);

export default defineComponent({
  name: 'BookmarkGrid',
  components: {
    AgGridVue
  },
  setup() {
    return {
      columnDefs: [
        { field: 'title', sortable: true, filter: true },
        { field: 'url', sortable: true, filter: true },
        { field: 'tags', sortable: true, filter: true },
        { field: 'notes', sortable: true, filter: true },
        { field: 'created', sortable: true, filter: true },
        { field: 'updated', sortable: true, filter: true }
      ],
      rowData: [
        { title: 'Google', url: 'https://www.google.com', tags: 'search', notes: 'search engine', created: '2021-01-01', updated: '2021-01-01' },
        { title: 'Vue.js', url: 'https://vuejs.org', tags: 'javascript', notes: 'frontend framework', created: '2021-01-01', updated: '2021-01-01' },
        { title: 'Bootstrap', url: 'https://getbootstrap.com', tags: 'css', notes: 'frontend framework', created: '2021-01-01', updated: '2021-01-01' },
        { title: 'GitHub', url: 'https://github.com', tags: 'git', notes: 'version control', created: '2021-01-01', updated: '2021-01-01' },
        { title: 'Stack Overflow', url: 'https://stackoverflow.com', tags: 'search', notes: 'programming community', created: '2021-01-01', updated: '2021-01-01' }
      ],
      theme: themeMaterial.withPart(colorSchemeDark),
    }
  }
});
</script>

<style scoped>
</style>
